### ISSUE TITLE
#7 2017 OpenLab Weekly

### ISSUE THREAD

**Issue by derphjl** [openlab-aux/openlab-weekly#1]
`7-2017 Newsletter will be posted on 19-Feb-2017` 
Kommentare mit Vorschlägen für den Newsletter.

**Comment by Profpatsch** [comment]
https://wiki.openlab-augsburg.de/Musikanlage dokumentiert & mpd eingerichtet

**Comment by Profpatsch** [comment]
Flora & Fritz-Mate

**Comment by waaaaargh** [comment]
Spontan-LAN-Party mit Quake 3 Arena

**Comment by Profpatsch** [comment]
Gutes Spiel.

**Comment by derphjl** [comment]
#2

**Comment by sternenseemann** [comment]
Bitte die Texte auch als Markdown im Repository einchecken, da wir kein funktionierendes Archiv für die ML haben.

Ich denke, das gibt eine schöne Historie, die hoffentlich Fortschritt und Blumenkraft zeigt.

**Comment by sternenseemann** [comment]
ping @phjlipp, please check in that stuff you know
