### ISSUE TITLE
#9 2017 OpenLab weekly

### ISSUE THREAD

**Issue by derphjl** [openlab-aux/openlab-weekly#2]
8-2017 Newsletter will be posted on 26-Feb-2017
Kommentare mit Vorschlägen für den Newsletter.

**Comment by derphjl** [comment]
KiCad-Kurs am Wochenende

**Comment by cko** [comment]
Linux-Infotag Orgatreffen am 4.3.

**Comment by derphjl** [comment]
9-2017 Newsletter will be posted on 5-Mar-2017

**Comment by muesli** [comment]
Announcing announcements. OpenLab goes Drachenlord.

**Comment by derphjl** [comment]
Platinen ätzen \o/

**Comment by Profpatsch** [comment]
Also jetzt monatlich?

Dann im nächsten Newsletter klarstellen, dass es jetzt monatlich sein wird und eventuell allen (~15) Unsubscribern der letzten Tage nochmal ne Mail schicken, dass es nicht wöchentlich sein wird.

**Comment by derphjl** [comment]
Ich probiere etwas rum damit. Gerade mal zweiwöchentlich. Mal sehen, wenn monatlich besser passt, dann so. Und den zweiten Vorschlag halte ich nicht für angemessen.

**Comment by derphjl** [comment]
Commitment Table und offene Montage

**Comment by derphjl** [comment]
#3
