### ISSUE TITLE
#10-11 2017 OpenLab weekly

### ISSUE THREAD

**Issue by derphjl** [openlab-aux/openlab-weekly#3]
10-11/2017 Newsletter will be posted on 19-Mar-2017
Kommentare mit Vorschlägen für den Newsletter.

**Comment by derphjl** [comment]
Plenum
siehe grob: https://ola.pads.ccc.de/plenum-2017-03-08

**Comment by derphjl** [comment]
Getränkeautomat oben!

**Comment by sternenseemann** [comment]
flipdot labping

**Comment by sternenseemann** [comment]
flipdots wieder komplett funktionstüchtig

**Comment by cko** [comment]
* NixOS MeetUp: https://openlab-augsburg.de/events/nixos-meetup-vortrag-zu-guix/
* 2(?) OpenLab Vorträge beim Augsburger Linux-Infotag: https://frab.nixos.community/de/lit2017/public/schedule/0

**Comment by Profpatsch** [comment]
Boden in der Küche & Vorraum gewischt https://wiki.openlab-augsburg.de/Boden%20putzen

**Comment by derphjl** [comment]
#4
